### ISSUE TITLE
Adding Link or Button into the Datatable row

### ISSUE THREAD

**Issue by OwenChia** [galenyuan/vue-datatable#2]
Hi,

How can I add link or Button as an element or content of a DataTable Row.
As if I click the link or Button in the DataTable row it will do some javascript work or go to some other pages.

**Comment by galenyuan** [comment]
Plan to add two options:
- isHTML: `Boolean`
- isButton: `Boolean`

If **isHTML** is true, will render text as a HTML string
If **isButton** is true, user should define a button array and will render buttons by the array

**Comment by galenyuan** [comment]
added in [this commit](https://github.com/galenyuan/vue-datatable/commit/c1627e67c50e5edc8fdf49e98acbc63ee10f2218)
